# Generated by Django 3.0.4 on 2020-09-30 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupManager',
            fields=[
                ('GroupID', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('Phone', models.CharField(max_length=20)),
                ('Nickname', models.CharField(max_length=20)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoryElements',
            fields=[
                ('SID', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('StoryName', models.CharField(max_length=250)),
                ('Story_Type', models.CharField(max_length=150)),
                ('Date_Created', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('StoryID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myweb.StoryElements')),
                ('Story_Article', models.TextField(max_length=999999)),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('Name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('BIO', models.CharField(max_length=250)),
                ('GID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.GroupManager')),
            ],
        ),
        migrations.AddField(
            model_name='storyelements',
            name='WID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.Writer'),
        ),
    ]
