# Generated by Django 2.2.7 on 2020-09-18 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupManager',
            fields=[
                ('GroupID', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('Username', models.CharField(max_length=250)),
                ('Password', models.CharField(max_length=250)),
                ('Role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('StoryID', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('StoryName', models.CharField(max_length=250)),
                ('Story_Article', models.TextField(max_length=999999)),
            ],
        ),
        migrations.CreateModel(
            name='StoryElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Story_Type', models.CharField(max_length=150)),
                ('Story_category', models.CharField(max_length=150)),
                ('SID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.Story')),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('WriterID', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=250)),
                ('BIO', models.CharField(max_length=250)),
                ('GID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myweb.GroupManager')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='storyelements',
            name='WID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.Writer'),
        ),
    ]
