# Generated by Django 3.0.4 on 2020-09-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_auto_20200930_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyelements',
            name='Date_Created',
            field=models.CharField(max_length=100),
        ),
    ]
