# Generated by Django 2.2.7 on 2020-09-24 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_auto_20200918_0707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storyelements',
            old_name='Story_category',
            new_name='Date_Created',
        ),
        migrations.RemoveField(
            model_name='groupmanager',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='groupmanager',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='groupmanager',
            name='Username',
        ),
        migrations.AlterField(
            model_name='groupmanager',
            name='Nickname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='groupmanager',
            name='Phone',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='writer',
            name='GID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.GroupManager'),
        ),
    ]
