# Generated by Django 3.0.4 on 2020-09-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_auto_20200930_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyelements',
            name='Date_Created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
