# Generated by Django 3.0.4 on 2020-09-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0004_auto_20200930_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyelements',
            name='AutoDate',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
